export default {
  login: "ali",
  id: 515861,
  node_id: "MDQ6VXNlcjUxNTg2MQ==",
  avatar_url: "https://avatars.githubusercontent.com/u/515861?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/ali",
  html_url: "https://github.com/ali",
  followers_url: "https://api.github.com/users/ali/followers",
  following_url: "https://api.github.com/users/ali/following{/other_user}",
  gists_url: "https://api.github.com/users/ali/gists{/gist_id}",
  starred_url: "https://api.github.com/users/ali/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/ali/subscriptions",
  organizations_url: "https://api.github.com/users/ali/orgs",
  repos_url: "https://api.github.com/users/ali/repos",
  events_url: "https://api.github.com/users/ali/events{/privacy}",
  received_events_url: "https://api.github.com/users/ali/received_events",
  type: "User",
  site_admin: false,
  name: "Ali Ukani",
  company: "@HubSpot",
  blog: "https://ali.io",
  location: "Somerville, MA",
  email: null,
  hireable: null,
  bio: "Senior SWE working on HubSpot's Frontend Platform",
  twitter_username: null,
  public_repos: 119,
  public_gists: 17,
  followers: 145,
  following: 329,
  created_at: "2010-12-09T07:01:12Z",
  updated_at: "2021-01-24T18:28:18Z",
};
